# Generated by Django 2.1.1 on 2018-10-10 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DairyApp', '0002_milk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milk',
            name='date',
            field=models.DateField(default='2018-6-8'),
        ),
        migrations.AlterField(
            model_name='milk',
            name='fat',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='milk',
            name='milkqty',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='milk',
            name='rate',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='milk',
            name='totalamt',
            field=models.IntegerField(),
        ),
    ]
