# Generated by Django 2.1.1 on 2018-10-17 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DairyApp', '0005_auto_20181010_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milkdata',
            name='fat',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='milkdata',
            name='milkqty',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='milkdata',
            name='rate',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='milkdata',
            name='totalamt',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
